name: 'Godot GUT CI'
description: 'Run Godot GUT tests on CI'
branding:
  icon: alert-triangle
  color: gray-dark
inputs:
  godot_version:
    description: 'Godot Version'
    required: false
    default: '3.2.2'
  unit_test:
    description: 'Unit tests path'
    required: true
  integration_test:
    description: 'Integration tests path'
    required: false
  output_file:
    description: 'File to redirect stdout to'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.godot_version }}
    - ${{ inputs.unit_test }}
    - ${{ inputs.integration_test }}
    - ${{ inputs.output_file }}
